apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-getweather
  labels: go-getweather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-getweather
  template:
    metadata:
      labels:
        app: go-getweather
    spec:
      containers:
        - name: go-getweather
          image: obetsa/go-getweather
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: go-getweather
spec:
  selector:
    app: go-getweather
  ports:
    - port: 8080
      targetPort: 8080
